name: Optimize resource pack
permissions: write-all
on: [push]
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
          
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = '.'
            output_file_path = '/tmp/pack.zip'
            
      - run: "sha1sum /tmp/pack.zip | awk '{ print $1 }' | tr -d \"\n\" > /tmp/hash.txt" # Generate Pack Hash
      
      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ResourcePack-v${{ github.run_number }}
          files: |
            /tmp/pack.zip
            /tmp/hash.txt
